<?
include_once('strategies/str_copycat.php');
include_once('strategies/str_copycat_forgiving.php');
include_once('strategies/str_copycat_rebalance.php');
include_once('strategies/str_copycat_trusted.php');
include_once('strategies/str_detective.php');
include_once('strategies/str_give.php');
include_once('strategies/str_random.php');
include_once('strategies/str_simpleton.php');
include_once('strategies/str_take.php');
include_once('strategies/str_unforgiving.php');
